import { useEffect, useMemo, useRef, useState } from "react";
import { BookOpen, Code2, ExternalLink, Globe2, Maximize2, RefreshCw, Search, X } from "lucide-react";

type AppRecord = { id: string; name: string; description: string; category: string; url: string; icon: string };
const icons = { youtube: Globe2, search: Search, book: BookOpen, github: Code2, code: Code2 } as const;
export default function Apps() {
  const [apps, setApps] = useState<AppRecord[]>([]); const [activeId, setActiveId] = useState(""); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [frameLoading, setFrameLoading] = useState(false); const [frameError, setFrameError] = useState(false); const frameRef = useRef<HTMLIFrameElement>(null);
  useEffect(() => { void fetch("/api/catalog/apps").then(async (response) => { if (!response.ok) throw new Error("Could not load Apps."); return response.json() as Promise<{ apps: AppRecord[] }>; }).then((result) => { setApps(result.apps); setActiveId(result.apps[0]?.id || ""); }).catch(() => setFrameError(true)).finally(() => setLoading(false)); }, []);
  const active = apps.find((app) => app.id === activeId); const filtered = useMemo(() => apps.filter((app) => `${app.name} ${app.description} ${app.category}`.toLowerCase().includes(query.toLowerCase())), [apps, query]);
  const launch = (app: AppRecord) => { setActiveId(app.id); setFrameLoading(true); setFrameError(false); };
  const reload = () => { if (!active || !frameRef.current) return; setFrameLoading(true); setFrameError(false); frameRef.current.src = active.url; };
  const fullscreen = () => { void frameRef.current?.requestFullscreen?.(); };
  if (loading) return <div className="profile-loading">loading Apps…</div>;
  return <div className="apps-page page-enter"><div className="page-title-row"><div><span className="eyebrow">Web apps</span><h1>Open the web inside Serene.</h1><p>Launch permitted destinations into the Serene viewport. Some sites may refuse framing.</p></div><div className="page-title-mark"><span>{apps.length.toString().padStart(2, "0")}</span><Globe2 size={19} /></div></div><div className="web-app-layout"><aside className="web-app-list"><label className="field-with-icon"><Search size={14} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Find a web app" /></label>{filtered.map((app) => { const Icon = icons[app.icon as keyof typeof icons] ?? Globe2; return <button key={app.id} className={active?.id === app.id ? "is-active" : ""} onClick={() => launch(app)}><span className="web-app-icon"><Icon size={15} /></span><span><strong>{app.name}</strong><small>{app.category}</small></span></button>; })}</aside><section className="web-app-view"><header><div><span className="eyebrow">{active?.category || "Apps"}</span><h2>{active?.name || "Choose an app"}</h2></div>{active && <div className="web-app-actions"><button className="icon-button" onClick={reload} aria-label="Reload"><RefreshCw size={15} /></button><button className="icon-button" onClick={fullscreen} aria-label="Fullscreen"><Maximize2 size={15} /></button><a className="icon-button" href={active.url} target="_blank" rel="noreferrer" aria-label="Open external fallback"><ExternalLink size={15} /></a></div>}</header><div className="web-app-frame-wrap">{active && !frameError ? <><iframe ref={frameRef} title={active.name} src={active.url} onLoad={() => setFrameLoading(false)} onError={() => { setFrameLoading(false); setFrameError(true); }} allow="autoplay; fullscreen; clipboard-read; clipboard-write" referrerPolicy="no-referrer-when-downgrade" />{frameLoading && <div className="frame-hint">Loading {active.name}…</div>}</> : <div className="studio-empty"><X size={20} /><strong>This destination cannot be displayed inside Serene.</strong><span>Use a supported permitted destination or choose the explicit external fallback.</span>{active && <a className="secondary-button small" href={active.url} target="_blank" rel="noreferrer">Open external fallback</a>}</div>}</div></section></div></div>;
}
