import { useMemo, useState } from "react";
import { ExternalLink, Globe2, Plus, RefreshCw, Search, X } from "lucide-react";
import { appRegistry } from "@/lib/data";

export default function Apps() {
  const [activeId, setActiveId] = useState(appRegistry[0].id);
  const [query, setQuery] = useState("");
  const active = appRegistry.find((app) => app.id === activeId) ?? appRegistry[0];
  const filtered = useMemo(() => appRegistry.filter((app) => `${app.name} ${app.description} ${app.category}`.toLowerCase().includes(query.toLowerCase())), [query]);
  return <div className="apps-page page-enter"><div className="page-title-row"><div><span className="eyebrow">Web apps</span><h1>Open the web inside Serene.</h1><p>Web destinations stay inside the Serene workspace whenever the destination allows embedded viewing.</p></div><div className="page-title-mark"><span>{appRegistry.length.toString().padStart(2, "0")}</span><Globe2 size={19} /></div></div><div className="web-app-layout"><aside className="web-app-list"><label className="field-with-icon"><Search size={14} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Find a web app" /></label>{filtered.map((app) => { const Icon = app.icon; return <button key={app.id} className={active.id === app.id ? "is-active" : ""} onClick={() => setActiveId(app.id)}><span className="web-app-icon"><Icon size={15} /></span><span><strong>{app.name}</strong><small>{app.category}</small></span></button>; })}<button className="web-app-add"><Plus size={14} /> Add web app</button></aside><section className="web-app-view"><header><div><span className="eyebrow">{active.category}</span><h2>{active.name}</h2></div><div className="web-app-actions"><button className="icon-button" onClick={() => document.getElementById("web-app-frame")?.setAttribute("src", active.url)} aria-label="Reload"><RefreshCw size={15} /></button><a className="icon-button" href={active.url} target="_blank" rel="noreferrer" aria-label="Open destination"><ExternalLink size={15} /></a></div></header><div className="web-app-frame-wrap"><iframe id="web-app-frame" title={active.name} src={active.url} allow="autoplay; fullscreen; clipboard-read; clipboard-write" referrerPolicy="no-referrer-when-downgrade" /><div className="frame-hint"><span>{active.description}</span><button onClick={() => setActiveId(active.id)}><X size={13} /></button></div></div></section></div></div>;
}
