import { FormEvent, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Bookmark, BookmarkCheck, Globe2, Home, Plus, RefreshCw, ShieldCheck, Sparkles, X } from "lucide-react";
import { useSerene } from "@/contexts/SereneContext";

function resolveInput(value: string) { const trimmed = value.trim(); if (!trimmed) return ""; if (/^https?:\/\//i.test(trimmed)) return trimmed; if (/^[\w-]+(\.[\w-]+)+([/?].*)?$/i.test(trimmed)) return `https://${trimmed}`; return `https://duckduckgo.com/?q=${encodeURIComponent(trimmed)}`; }
function NewTab({ onNavigate }: { onNavigate: (value: string) => void }) { const [input, setInput] = useState(""); const submit = (e: FormEvent) => { e.preventDefault(); onNavigate(input); }; return <div className="new-tab-view"><div className="new-tab-center"><div className="new-tab-mark"><Sparkles size={19} /></div><span className="eyebrow">Serene browser</span><h1>Where to next?</h1><form className="new-tab-search" onSubmit={submit}><Globe2 size={17} /><input autoFocus value={input} onChange={(e) => setInput(e.target.value)} placeholder="Search or enter an address" /><kbd>↵</kbd></form><div className="shortcut-row"><button onClick={() => onNavigate("https://duckduckgo.com")}><span>DDG</span> DuckDuckGo</button><button onClick={() => onNavigate("https://www.youtube.com")}><span>YT</span> YouTube</button><button onClick={() => onNavigate("https://github.com")}><span>GH</span> GitHub</button></div></div></div>; }
export default function Browser() {
  const { browserTabs, activeBrowserTab, setActiveBrowserTab, addBrowserTab, closeBrowserTab, updateBrowserTab, bookmarks, addBookmark, removeBookmark, addHistory } = useSerene();
  const [address, setAddress] = useState("");
  const active = browserTabs.find((tab) => tab.id === activeBrowserTab) ?? browserTabs[0];
  const bookmarked = bookmarks.includes(active.url);
  const isNewTab = active.url === "serene://new-tab";
  const displayUrl = useMemo(() => active.url.replace(/^https?:\/\//, "").replace(/\/$/, ""), [active.url]);
  const navigate = (value: string) => { const destination = resolveInput(value); if (!destination) return; if (destination.startsWith("serene://")) { updateBrowserTab(active.id, { title: "New tab", url: destination }); return; } const host = destination.replace(/^https?:\/\//, "").split("/")[0]; updateBrowserTab(active.id, { title: host || "Web page", url: destination, loading: true }); setAddress(""); addHistory(destination); window.setTimeout(() => updateBrowserTab(active.id, { loading: false }), 450); };
  const goHome = () => updateBrowserTab(active.id, { title: "New tab", url: "serene://new-tab" });
  return <div className="browser-page page-enter"><div className="browser-tabs"><div className="browser-tab-list">{browserTabs.map((tab) => <button key={tab.id} className={`browser-tab ${tab.id === active.id ? "is-active" : ""}`} onClick={() => setActiveBrowserTab(tab.id)}><span>{tab.loading ? <RefreshCw size={11} className="spin" /> : <Globe2 size={11} />}</span><span>{tab.title}</span>{browserTabs.length > 1 && <i onClick={(e) => { e.stopPropagation(); closeBrowserTab(tab.id); }}><X size={12} /></i>}</button>)}</div><button className="new-tab-button" onClick={addBrowserTab}><Plus size={15} /></button></div><div className="browser-toolbar"><div className="browser-controls"><button className="icon-button" onClick={() => window.history.back()}><ArrowLeft size={16} /></button><button className="icon-button" onClick={() => window.history.forward()}><ArrowRight size={16} /></button><button className="icon-button" onClick={() => active.url !== "serene://new-tab" && navigate(active.url)}><RefreshCw size={15} /></button><button className="icon-button" onClick={goHome}><Home size={16} /></button></div><form className="address-bar" onSubmit={(e) => { e.preventDefault(); navigate(address); }}><ShieldCheck size={14} /><input value={address || displayUrl} onChange={(e) => setAddress(e.target.value)} /><button type="button" onClick={() => bookmarked ? removeBookmark(active.url) : addBookmark(active.url)}>{bookmarked ? <BookmarkCheck size={15} /> : <Bookmark size={15} />}</button></form></div><div className="browser-viewport">{isNewTab ? <NewTab onNavigate={navigate} /> : <div className="browser-embed"><iframe title={active.title} src={active.url} allow="autoplay; fullscreen; clipboard-read; clipboard-write" referrerPolicy="no-referrer-when-downgrade" /><div className="browser-embed-bar"><ShieldCheck size={13} /><span>Viewing inside Serene. Some sites may refuse embedding.</span><a href={active.url} target="_blank" rel="noreferrer">Open externally</a></div></div>}</div></div>;
}
