import { useEffect, useMemo, useState } from "react";
import { Hash, MessageCircle, Plus, Settings2, Users, X } from "lucide-react";
import { useAuth } from "@/contexts/AuthContext";

type Server = { id: string; name: string; icon: string; ownerId: string };
type Channel = { id: string; name: string; category: string; categoryId: string };
type Message = { id: string; body: string; authorId: string; username: string; createdAt: string };
async function api<T>(path: string, options?: RequestInit) { const response = await fetch(path, { credentials: "include", headers: { "Content-Type": "application/json", ...(options?.headers ?? {}) }, ...options }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "Chat request failed."); return data as T; }
export default function Chat() {
  const { user } = useAuth(); const [servers, setServers] = useState<Server[]>([]); const [serverId, setServerId] = useState(""); const [channels, setChannels] = useState<Channel[]>([]); const [channelId, setChannelId] = useState(""); const [messages, setMessages] = useState<Message[]>([]); const [draft, setDraft] = useState(""); const [ownerTools, setOwnerTools] = useState(false); const [newChannel, setNewChannel] = useState(""); const [newServer, setNewServer] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const server = servers.find((item) => item.id === serverId); const channel = channels.find((item) => item.id === channelId); const grouped = useMemo(() => channels.reduce<Record<string, Channel[]>>((acc, item) => { (acc[item.category] ??= []).push(item); return acc; }, {}), [channels]);
  const loadServers = async () => { const result = await api<{ servers: Server[] }>("/api/chat/servers"); setServers(result.servers); if (!serverId && result.servers[0]) setServerId(result.servers[0].id); };
  const loadChannels = async (id: string) => { const result = await api<{ channels: Channel[] }>(`/api/chat/servers/${id}/channels`); setChannels(result.channels); setChannelId((current) => result.channels.some((item) => item.id === current) ? current : result.channels[0]?.id || ""); };
  const loadMessages = async (id: string) => { const result = await api<{ messages: Message[] }>(`/api/chat/channels/${id}/messages`); setMessages(result.messages); };
  useEffect(() => { void loadServers().catch((err: Error) => setError(err.message)).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (serverId) void loadChannels(serverId).catch((err: Error) => setError(err.message)); }, [serverId]);
  useEffect(() => { if (channelId) void loadMessages(channelId).catch((err: Error) => setError(err.message)); }, [channelId]);
  const send = async () => { const body = draft.trim(); if (!body || !channelId) return; try { const result = await api<{ message: Message }>(`/api/chat/channels/${channelId}/messages`, { method: "POST", body: JSON.stringify({ body }) }); setMessages((current) => [...current, result.message]); setDraft(""); } catch (err) { setError(err instanceof Error ? err.message : "Could not send message."); } };
  const createServer = async () => { const name = newServer.trim(); if (!name) return; try { const result = await api<{ server: Server }>("/api/chat/servers", { method: "POST", body: JSON.stringify({ name }) }); setServers((current) => [...current, result.server]); setServerId(result.server.id); setNewServer(""); } catch (err) { setError(err instanceof Error ? err.message : "Could not create server."); } };
  const createChannel = async () => { const name = newChannel.trim(); if (!name || !serverId) return; try { const result = await api<{ channel: Channel }>(`/api/chat/servers/${serverId}/channels`, { method: "POST", body: JSON.stringify({ name }) }); setChannels((current) => [...current, result.channel]); setChannelId(result.channel.id); setNewChannel(""); } catch (err) { setError(err instanceof Error ? err.message : "Could not create channel."); } };
  if (loading) return <div className="profile-loading">loading chat…</div>;
  if (!user) return <div className="chat-page page-enter"><div className="studio-empty">Sign in to join Serene chat.</div></div>;
  return <div className="chat-page page-enter"><div className="page-title-row compact-title"><div><span className="eyebrow">Community</span><h1>Chat rooms.</h1><p>Servers, categories, and channels that stay inside Serene.</p></div>{(user.role === "owner" || user.role === "admin") && <button className={`secondary-button small ${ownerTools ? "is-active" : ""}`} onClick={() => setOwnerTools((value) => !value)}><Settings2 size={14} /> Owner tools</button>}</div>{error && <div className="auth-error">{error}<button onClick={() => setError("")} aria-label="Dismiss"><X size={13} /></button></div>}<div className="chat-shell"><aside className="server-rail">{servers.map((item) => <button key={item.id} className={item.id === server?.id ? "is-active" : ""} title={item.name} onClick={() => setServerId(item.id)}><span>{item.name.slice(0, 1).toUpperCase()}</span></button>)}{ownerTools && <button className="server-add" onClick={() => setNewServer(" ")}><Plus size={16} /></button>}</aside><aside className="channel-rail"><div className="channel-head"><strong>{server?.name || "No server"}</strong><Users size={15} /></div>{Object.entries(grouped).map(([category, items]) => <div className="channel-group" key={category}><span>{category}</span>{items.map((item) => <button key={item.id} className={item.id === channel?.id ? "is-active" : ""} onClick={() => setChannelId(item.id)}><Hash size={14} />{item.name}</button>)}</div>)}{!channels.length && <div className="studio-empty">No channels yet.</div>}{ownerTools && <div className="owner-chat-tools"><input value={newChannel} onChange={(e) => setNewChannel(e.target.value)} placeholder="new channel" /><button onClick={() => void createChannel()}>Add</button><input value={newServer} onChange={(e) => setNewServer(e.target.value)} placeholder="new server" /><button onClick={() => void createServer()}>Add</button></div>}</aside><section className="chat-main"><header className="chat-main-head"><div><span className="eyebrow">Channel</span><h2><Hash size={17} /> {channel?.name || "Choose a channel"}</h2></div><MessageCircle size={18} /></header><div className="message-list">{messages.length ? messages.map((message) => <article className="message-row" key={message.id}><span className="message-avatar">{message.username.slice(0, 1).toUpperCase()}</span><div><strong>{message.username}</strong><small>{new Date(message.createdAt).toLocaleString()}</small><p>{message.body}</p></div></article>) : <div className="chat-empty">No messages here yet. Start the conversation.</div>}</div><form className="chat-composer" onSubmit={(event) => { event.preventDefault(); void send(); }}><input value={draft} onChange={(event) => setDraft(event.target.value)} disabled={!channelId} placeholder={channelId ? `Message #${channel?.name}` : "Choose a channel first"} /><button className="primary-button small" disabled={!draft.trim() || !channelId}>Send</button></form></section></div></div>;
}
