import { useMemo, useState } from "react";
import { ArrowUpRight, Bookmark, Clock3, Gamepad2, Search as SearchIcon, Settings2, Sparkles, X } from "lucide-react";
import { Link } from "wouter";
import { appRegistry, games } from "@/lib/data";
import { useSerene } from "@/contexts/SereneContext";

export default function SearchPage() {
  const [query, setQuery] = useState("");
  const { bookmarks, browserHistory } = useSerene();
  const q = query.toLowerCase().trim();
  const gameResults = useMemo(() => games.filter((game) => `${game.title} ${game.description} ${game.category}`.toLowerCase().includes(q)), [q]);
  const appResults = useMemo(() => appRegistry.filter((app) => `${app.name} ${app.description} ${app.category}`.toLowerCase().includes(q)), [q]);
  const browserResults = [...bookmarks, ...browserHistory].filter((item, index, list) => list.indexOf(item) === index && item.toLowerCase().includes(q));
  return <div className="search-page page-enter"><div className="search-hero"><div><span className="eyebrow">Global index</span><h1>Find your next place.</h1><p>Search across the things that make Serene yours.</p></div><span className="search-hero-count">{q ? gameResults.length + appResults.length + browserResults.length : "⌘ K"}</span></div><label className="global-search-field"><SearchIcon size={20} /><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Games, apps, bookmarks, history…" aria-label="Global search" />{query && <button onClick={() => setQuery("")} aria-label="Clear search"><X size={16} /></button>}<kbd>Esc</kbd></label>{!q ? <div className="search-suggestions"><span className="eyebrow">Try looking for</span><div className="suggestion-row"><button onClick={() => setQuery("puzzle")}>puzzle games</button><button onClick={() => setQuery("timer")}>timer</button><button onClick={() => setQuery("writing")}>writing tools</button><button onClick={() => setQuery("github")}>GitHub</button></div><div className="search-suggestion-art"><Sparkles size={18} /><span>Every result is local to this session, except destinations you choose to visit.</span></div></div> : <div className="search-results"><ResultGroup icon={Gamepad2} label="Games" count={gameResults.length}>{gameResults.map((game) => <Link className="result-row" href={`/games/${game.id}`} key={game.id}><span className="result-thumb" style={{ backgroundImage: `url(${game.image})` }} /><span><strong>{game.title}</strong><small>{game.category} · {game.description}</small></span><ArrowUpRight size={15} /></Link>)}</ResultGroup><ResultGroup icon={Sparkles} label="Apps" count={appResults.length}>{appResults.map((app) => { const Icon = app.icon; return <Link className="result-row" href="/apps" key={app.id}><span className="result-icon"><Icon size={15} /></span><span><strong>{app.name}</strong><small>{app.category} · {app.description}</small></span><ArrowUpRight size={15} /></Link>; })}</ResultGroup><ResultGroup icon={Bookmark} label="Bookmarks & history" count={browserResults.length}>{browserResults.map((item) => <a className="result-row" href={item.startsWith("http") ? item : "/browser"} target={item.startsWith("http") ? "_blank" : undefined} rel="noreferrer" key={item}><span className="result-icon"><Clock3 size={15} /></span><span><strong>{item.replace(/^https?:\/\//, "")}</strong><small>Browser destination</small></span><ArrowUpRight size={15} /></a>)}</ResultGroup>{gameResults.length + appResults.length + browserResults.length === 0 && <div className="empty-state"><SearchIcon size={22} /><h3>No quiet match yet.</h3><p>Try a title, a category, or a tool name.</p></div>}</div>}</div>;
}

function ResultGroup({ icon: Icon, label, count, children }: { icon: React.ComponentType<{ size?: number }>; label: string; count: number; children: React.ReactNode }) { return <section className="result-group"><div className="result-group-heading"><span><Icon size={15} /> {label}</span><small>{count}</small></div>{count > 0 ? children : <div className="result-group-empty">Nothing here for this search.</div>}</section>; }
