import { useEffect, useMemo, useState } from "react";
import { Crown, Disc3, Gem, Sparkles, Star, WandSparkles } from "lucide-react";
import { useAuth } from "@/contexts/AuthContext";
import ProfileOrb from "@/components/ProfileOrb";

type ShopItem = { id: string; name: string; description: string; price: number; kind: string; value: string };
type Transaction = { id: string; amount: number; kind: string; createdAt: string };
const icons = { theme: Gem, particles: WandSparkles, avatarAnimation: Disc3, avatarFrame: Crown } as const;
const labels = { theme: "Themes", particles: "Particles", avatarAnimation: "Avatar Animations", avatarFrame: "Profile Frames" } as const;
async function api<T>(path: string, options?: RequestInit) { const response = await fetch(path, { credentials: "include", headers: { "Content-Type": "application/json", ...(options?.headers ?? {}) }, ...options }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "Shop request failed."); return data as T; }

export default function Shop() {
  const { user, loading: authLoading, buyItem, equipItem, unequipItem } = useAuth();
  const [items, setItems] = useState<ShopItem[]>([]); const [transactions, setTransactions] = useState<Transaction[]>([]); const [filter, setFilter] = useState("All"); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => { if (!user) { setLoading(false); return; } void Promise.all([api<{ items: ShopItem[] }>("/api/shop/items"), api<{ transactions: Transaction[] }>("/api/stars/transactions")]).then(([catalog, ledger]) => { setItems(catalog.items); setTransactions(ledger.transactions); }).catch((err: Error) => setError(err.message)).finally(() => setLoading(false)); }, [user]);
  const filters = ["All", ...Array.from(new Set(items.map((item) => item.kind)))]; const visible = useMemo(() => filter === "All" ? items : items.filter((item) => item.kind === filter), [filter, items]);
  if (authLoading) return <div className="shop-page page-enter"><div className="profile-loading">Loading Shop...</div></div>;
  if (!user) return <div className="shop-page page-enter"><div className="shop-login-note">Sign in to spend Stars in the Serene Shop.</div></div>;
  const purchase = async (item: ShopItem) => { if (!window.confirm(`Purchase ${item.name} for ${item.price.toLocaleString()} Stars?`)) return; setBusy(item.id); setError(""); try { await buyItem(item.id); const ledger = await api<{ transactions: Transaction[] }>("/api/stars/transactions"); setTransactions(ledger.transactions); } catch (err) { setError(err instanceof Error ? err.message : "Purchase failed."); } finally { setBusy(""); } };
  const equip = async (item: ShopItem) => { setBusy(item.id); setError(""); try { await equipItem(item.id); } catch (err) { setError(err instanceof Error ? err.message : "Could not equip item."); } finally { setBusy(""); } };
  const unequip = async (item: ShopItem) => { setBusy(item.id); try { await unequipItem(item.kind === "theme" ? "theme" : item.kind); } catch (err) { setError(err instanceof Error ? err.message : "Could not unequip item."); } finally { setBusy(""); } };
  return <div className="shop-page page-enter"><div className="shop-head"><div><span className="eyebrow">Serene Shop</span><h1>Make the whole space yours.</h1><p>Ownership, balances, and purchases are validated and stored with your account.</p></div><div className="shop-wallet"><Star size={17} /><strong>{user.stars.toLocaleString()}</strong><span>Stars</span></div></div>{error && <div className="auth-error">{error}</div>}{loading ? <div className="profile-loading">Loading Shop...</div> : <><div className="shop-profile-strip"><ProfileOrb username={user.username} animation={user.avatarAnimation} frame={user.avatarFrame} size="sm" /><div><strong>@{user.username}</strong><span>{user.ownedItems.length} owned items</span></div><div className="shop-profile-effects"><span>{user.siteTheme}</span><span>{user.particles}</span><span>{user.avatarAnimation}</span></div></div><div className="shop-filters">{filters.map((item) => <button key={item} className={filter === item ? "is-active" : ""} onClick={() => setFilter(item)}>{labels[item as keyof typeof labels] || item}</button>)}</div><div className="shop-grid">{visible.map((item) => { const Icon = icons[item.kind as keyof typeof icons] || Sparkles; const owned = user.ownedItems.includes(item.id); const equipped = (item.kind === "theme" && user.siteTheme === item.value) || (item.kind === "particles" && user.particles === item.value) || (item.kind === "avatarAnimation" && user.avatarAnimation === item.value) || (item.kind === "avatarFrame" && user.avatarFrame === item.value); return <article className={`shop-item ${owned ? "is-owned" : ""}`} key={item.id}><div className="shop-item-art"><Icon size={25} /><div className="shop-item-orbit" /></div><div className="shop-item-copy"><span>{labels[item.kind as keyof typeof labels] || item.kind}</span><h2>{item.name}</h2><p>{item.description}</p></div><div className="shop-item-buy">{owned ? <button className={`secondary-button small ${equipped ? "is-active" : ""}`} disabled={busy === item.id} onClick={() => void (equipped ? unequip(item) : equip(item))}>{busy === item.id ? "Working..." : equipped ? "Equipped" : "Equip"}</button> : <button className="primary-button small" disabled={busy === item.id} onClick={() => void purchase(item)}>{busy === item.id ? "Buying..." : <><Star size={12} /> {item.price}</>}</button>}</div></article>; })}</div><div className="shop-ledger"><span className="eyebrow">Recent Star activity</span>{transactions.slice(0, 5).map((item) => <span key={item.id}>{item.amount > 0 ? "+" : ""}{item.amount} Stars · {item.kind}</span>)}</div></>}</div>;
}
