import { useEffect, useMemo, useState } from "react";
import { Check, Crown, Disc3, Gem, Sparkles, Star, WandSparkles } from "lucide-react";
import { useAuth } from "@/contexts/AuthContext";
import ProfileOrb from "@/components/ProfileOrb";

type ShopItem = { id: string; name: string; description: string; price: number; kind: string; value: string };
type Transaction = { id: string; amount: number; kind: string; createdAt: string };
const icons = { theme: Gem, particles: WandSparkles, avatarAnimation: Disc3, avatarFrame: Crown } as const;
const labels = { theme: "Themes", particles: "Particles", avatarAnimation: "Avatar animation", avatarFrame: "Profile frame" } as const;
export default function Shop() {
  const { user, buyItem, equipItem, unequipItem } = useAuth(); const [items, setItems] = useState<ShopItem[]>([]); const [transactions, setTransactions] = useState<Transaction[]>([]); const [filter, setFilter] = useState("All"); const [busy, setBusy] = useState(""); const [error, setError] = useState("");
  useEffect(() => { void Promise.all([fetch("/api/shop/items").then((response) => response.json() as Promise<{ items: ShopItem[] }>), user ? fetch("/api/stars/transactions", { credentials: "include" }).then((response) => response.json() as Promise<{ transactions: Transaction[] }>) : Promise.resolve({ transactions: [] })]).then(([itemResult, transactionResult]) => { setItems(itemResult.items); setTransactions(transactionResult.transactions); }).catch(() => setError("Could not load the Serene Shop.")); }, [user]);
  const filters = ["All", ...Array.from(new Set(items.map((item) => item.kind)))]; const visible = useMemo(() => filter === "All" ? items : items.filter((item) => item.kind === filter), [filter, items]);
  if (!user) return <div className="shop-page page-enter"><div className="shop-login-note">sign in to spend Stars in the Serene Shop.</div></div>;
  const purchase = async (id: string) => { setBusy(id); setError(""); try { await buyItem(id); const result = await fetch("/api/stars/transactions", { credentials: "include" }).then((response) => response.json() as Promise<{ transactions: Transaction[] }>); setTransactions(result.transactions); } catch (err) { setError(err instanceof Error ? err.message : "Purchase failed."); } finally { setBusy(""); } };
  const equip = async (item: ShopItem) => { setBusy(item.id); setError(""); try { await equipItem(item.id); } catch (err) { setError(err instanceof Error ? err.message : "Could not equip item."); } finally { setBusy(""); } };
  return <div className="shop-page page-enter"><div className="shop-head"><div><span className="eyebrow">Serene Shop</span><h1>make the whole space yours.</h1><p>The catalog, balance, ownership, and purchases are stored with your account.</p></div><div className="shop-wallet"><Star size={17} /><strong>{user.stars.toLocaleString()}</strong><span>Stars</span></div></div>{error && <div className="auth-error">{error}</div>}<div className="shop-profile-strip"><ProfileOrb username={user.username} animation={user.avatarAnimation} frame={user.avatarFrame} size="sm" /><div><strong>@{user.username}</strong><span>{user.ownedItems.length} owned items</span></div><div className="shop-profile-effects"><span>{user.siteTheme}</span><span>{user.particles}</span><span>{user.avatarAnimation}</span></div></div><div className="shop-filters">{filters.map((item) => <button key={item} className={filter === item ? "is-active" : ""} onClick={() => setFilter(item)}>{labels[item as keyof typeof labels] || item}</button>)}</div><div className="shop-grid">{visible.map((item) => { const Icon = icons[item.kind as keyof typeof icons] || Sparkles; const owned = user.ownedItems.includes(item.id); const equipped = (item.kind === "theme" && user.siteTheme === item.value) || (item.kind === "particles" && user.particles === item.value) || (item.kind === "avatarAnimation" && user.avatarAnimation === item.value) || (item.kind === "avatarFrame" && user.avatarFrame === item.value); return <article className={`shop-item ${owned ? "is-owned" : ""}`} key={item.id}><div className="shop-item-art"><Icon size={25} /><div className="shop-item-orbit" /></div><div className="shop-item-copy"><span>{labels[item.kind as keyof typeof labels] || item.kind}</span><h2>{item.name}</h2><p>{item.description}</p></div><div className="shop-item-buy">{owned ? <button className={`secondary-button small ${equipped ? "is-active" : ""}`} disabled={busy === item.id} onClick={() => equipped ? void unequipItem(item.kind === "theme" ? "theme" : item.kind) : void equip(item)}>{equipped ? <><Check size={14} /> Equipped</> : "Equip"}</button> : <button className="primary-button small" disabled={busy === item.id || user.stars < item.price} onClick={() => void purchase(item.id)}><Star size={13} /> {busy === item.id ? "Buying…" : item.price}</button>}</div></article>; })}</div><section className="shop-history"><div className="card-heading"><div><span className="eyebrow">Ledger</span><h2>Stars history</h2></div><Star size={17} /></div>{transactions.length ? transactions.slice(0, 8).map((transaction) => <div className="transaction-row" key={transaction.id}><span>{transaction.kind}</span><strong className={transaction.amount > 0 ? "is-positive" : ""}>{transaction.amount > 0 ? "+" : ""}{transaction.amount} Stars</strong><small>{new Date(transaction.createdAt).toLocaleDateString()}</small></div>) : <div className="studio-empty">No Stars transactions yet.</div>}</section></div>;
}
